server:
  ip: 47.116.21.234
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.116.21.234:3306/mynews?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  main:
      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis:
        mapper-locations: classpath:mapper/*.xml
# configuration:
  ##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
    path: /home/files/


